"""Run from AMR-DVB-S2X/ to append Section 7 (1D CNN with PyTorch) to the notebook."""
import json, os

NB_PATH = os.path.join("notebooks", "AMR_DVB_S2X.ipynb")

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Remove existing CNN cells if re-running
nb["cells"] = [c for c in nb["cells"]
               if "Conv1d" not in "".join(c.get("source", []))
               and "Section 7" not in "".join(c.get("source", []))]

def code_cell(src):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": [src]}

def md_cell(src):
    return {"cell_type": "markdown", "metadata": {}, "source": [src]}


nb["cells"].append(md_cell(
    "## Section 7 — 1D CNN on Raw I/Q (Best Accuracy)\n"
    "A 1D Convolutional Neural Network operating directly on raw I/Q signals.\n"
    "No hand-crafted features needed — the CNN learns patterns automatically.\n\n"
    "Architecture: `Input(128,2)` → Conv1d(64)→BN→Pool → Conv1d(128)→BN→Pool → Conv1d(256)→BN → AdaptiveAvgPool → Linear(128) → Linear(2)\n\n"
    "**Expected: ~90–95% accuracy at high SNR.**"
))

nb["cells"].append(code_cell(
    "try:\n"
    "    import torch\n"
    "    import torch.nn as nn\n"
    "    from torch.utils.data import TensorDataset, DataLoader\n"
    "    TORCH_AVAILABLE = True\n"
    "    print(f'PyTorch version: {torch.__version__}')\n"
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "    print(f'Device: {device}')\n"
    "except ImportError:\n"
    "    TORCH_AVAILABLE = False\n"
    "    print('[WARN] PyTorch not installed. Run: pip install torch')\n"
))

nb["cells"].append(code_cell(
    "if TORCH_AVAILABLE:\n"
    "    from sklearn.preprocessing import LabelEncoder\n"
    "    le_cnn = LabelEncoder()\n"
    "\n"
    "    # Same 80/20 stratified split on raw I/Q\n"
    "    X_raw_tr, X_raw_te, y_raw_tr, y_raw_te, snrs_raw_tr, snrs_raw_te = train_test_split(\n"
    "        X, y, snrs, test_size=0.2, random_state=42, stratify=y\n"
    "    )\n"
    "\n"
    "    # PyTorch Conv1d expects (N, channels, timesteps) = (N, 2, 128)\n"
    "    X_tr_t = torch.tensor(X_raw_tr, dtype=torch.float32)   # already (N, 2, 128)\n"
    "    X_te_t = torch.tensor(X_raw_te, dtype=torch.float32)\n"
    "    y_tr_t = torch.tensor(le_cnn.fit_transform(y_raw_tr), dtype=torch.long)\n"
    "    y_te_t = torch.tensor(le_cnn.transform(y_raw_te),     dtype=torch.long)\n"
    "\n"
    "    train_loader = DataLoader(TensorDataset(X_tr_t, y_tr_t), batch_size=256, shuffle=True)\n"
    "    test_loader  = DataLoader(TensorDataset(X_te_t, y_te_t), batch_size=512)\n"
    "\n"
    "    # ── 1D CNN model ────────────────────────────────────────────────────\n"
    "    class CNN1D(nn.Module):\n"
    "        def __init__(self, num_classes=2):\n"
    "            super().__init__()\n"
    "            self.net = nn.Sequential(\n"
    "                nn.Conv1d(2,  64,  7, padding=3), nn.BatchNorm1d(64),  nn.ReLU(), nn.MaxPool1d(2),\n"
    "                nn.Conv1d(64, 128, 5, padding=2), nn.BatchNorm1d(128), nn.ReLU(), nn.MaxPool1d(2),\n"
    "                nn.Conv1d(128,256, 3, padding=1), nn.BatchNorm1d(256), nn.ReLU(),\n"
    "                nn.AdaptiveAvgPool1d(1),\n"
    "            )\n"
    "            self.head = nn.Sequential(\n"
    "                nn.Flatten(),\n"
    "                nn.Linear(256, 128), nn.ReLU(), nn.Dropout(0.3),\n"
    "                nn.Linear(128, num_classes)\n"
    "            )\n"
    "        def forward(self, x):\n"
    "            return self.head(self.net(x))\n"
    "\n"
    "    model = CNN1D().to(device)\n"
    "    print(model)\n"
    "    print(f'Parameters: {sum(p.numel() for p in model.parameters()):,}')\n"
    "\n"
    "    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)\n"
    "    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, factor=0.5)\n"
    "    criterion = nn.CrossEntropyLoss()\n"
    "\n"
    "    train_accs, val_accs, train_losses, val_losses = [], [], [], []\n"
    "    best_val_acc = 0.0\n"
    "    patience_counter = 0\n"
    "\n"
    "    print('Training 1D CNN ...')\n"
    "    for epoch in range(50):\n"
    "        # Train\n"
    "        model.train()\n"
    "        total_loss, correct, total = 0.0, 0, 0\n"
    "        for xb, yb in train_loader:\n"
    "            xb, yb = xb.to(device), yb.to(device)\n"
    "            optimizer.zero_grad()\n"
    "            out = model(xb)\n"
    "            loss = criterion(out, yb)\n"
    "            loss.backward()\n"
    "            optimizer.step()\n"
    "            total_loss += loss.item() * len(yb)\n"
    "            correct += (out.argmax(1) == yb).sum().item()\n"
    "            total += len(yb)\n"
    "        train_losses.append(total_loss / total)\n"
    "        train_accs.append(correct / total)\n"
    "\n"
    "        # Validate\n"
    "        model.eval()\n"
    "        val_loss, val_correct, val_total = 0.0, 0, 0\n"
    "        with torch.no_grad():\n"
    "            for xb, yb in test_loader:\n"
    "                xb, yb = xb.to(device), yb.to(device)\n"
    "                out = model(xb)\n"
    "                val_loss += criterion(out, yb).item() * len(yb)\n"
    "                val_correct += (out.argmax(1) == yb).sum().item()\n"
    "                val_total += len(yb)\n"
    "        val_losses.append(val_loss / val_total)\n"
    "        val_accs.append(val_correct / val_total)\n"
    "        scheduler.step(val_losses[-1])\n"
    "\n"
    "        if val_accs[-1] > best_val_acc:\n"
    "            best_val_acc = val_accs[-1]\n"
    "            patience_counter = 0\n"
    "        else:\n"
    "            patience_counter += 1\n"
    "\n"
    "        if (epoch + 1) % 5 == 0:\n"
    "            print(f'Epoch {epoch+1:3d} | train_acc={train_accs[-1]:.4f} | val_acc={val_accs[-1]:.4f} | lr={optimizer.param_groups[0][\"lr\"]:.2e}')\n"
    "\n"
    "        if patience_counter >= 10:\n"
    "            print(f'Early stopping at epoch {epoch+1}')\n"
    "            break\n"
    "\n"
    "    print(f'Best CNN Validation Accuracy: {best_val_acc * 100:.2f}%')\n"
    "else:\n"
    "    print('PyTorch not available - skipping CNN section.')\n"
))

nb["cells"].append(code_cell(
    "if TORCH_AVAILABLE:\n"
    "    # Training curves\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "    axes[0].plot(train_accs, label='Train', color='steelblue')\n"
    "    axes[0].plot(val_accs,   label='Val',   color='tomato')\n"
    "    axes[0].set_title('CNN Accuracy'); axes[0].set_xlabel('Epoch')\n"
    "    axes[0].set_ylabel('Accuracy'); axes[0].legend()\n"
    "    axes[1].plot(train_losses, label='Train', color='steelblue')\n"
    "    axes[1].plot(val_losses,   label='Val',   color='tomato')\n"
    "    axes[1].set_title('CNN Loss'); axes[1].set_xlabel('Epoch')\n"
    "    axes[1].set_ylabel('Loss'); axes[1].legend()\n"
    "    plt.suptitle('1D CNN Training Curves', fontsize=14, fontweight='bold')\n"
    "    plt.tight_layout(); plt.show()\n"
    "\n"
    "    # Accuracy per SNR\n"
    "    model.eval()\n"
    "    all_preds = []\n"
    "    with torch.no_grad():\n"
    "        for xb, _ in test_loader:\n"
    "            all_preds.append(model(xb.to(device)).argmax(1).cpu().numpy())\n"
    "    import numpy as np_tmp\n"
    "    y_cnn_pred = np_tmp.concatenate(all_preds)\n"
    "    y_cnn_true = le_cnn.transform(y_raw_te)\n"
    "    cnn_acc = (y_cnn_pred == y_cnn_true).mean()\n"
    "\n"
    "    unique_snrs_te = sorted(set(snrs_raw_te))\n"
    "    cnn_acc_snr = [\n"
    "        (y_cnn_pred[snrs_raw_te == s] == y_cnn_true[snrs_raw_te == s]).mean() * 100\n"
    "        for s in unique_snrs_te\n"
    "    ]\n"
    "\n"
    "    fig, ax = plt.subplots(figsize=(12, 5))\n"
    "    ax.plot(unique_snrs_te, cnn_acc_snr, marker='o', linewidth=2, color='darkorange', label='1D CNN')\n"
    "    if XGBOOST_AVAILABLE:\n"
    "        xgb_acc_snr = [\n"
    "            accuracy_score(y_test[snrs_test == s], y_pred_xgb[snrs_test == s]) * 100\n"
    "            for s in unique_snrs_te\n"
    "        ]\n"
    "        ax.plot(unique_snrs_te, xgb_acc_snr, marker='s', linewidth=2, color='steelblue', label='XGBoost')\n"
    "    ax.axhline(50, color='red',   linestyle='--', linewidth=1, label='Random baseline')\n"
    "    ax.axhline(90, color='green', linestyle='--', linewidth=1, label='90% target')\n"
    "    ax.set_xlabel('SNR (dB)', fontsize=12); ax.set_ylabel('Accuracy (%)', fontsize=12)\n"
    "    ax.set_title('CNN vs XGBoost — Accuracy per SNR', fontsize=14)\n"
    "    ax.set_ylim(0, 105); ax.set_xticks(unique_snrs_te); ax.grid(True, alpha=0.4); ax.legend()\n"
    "    plt.tight_layout()\n"
    "    plt.savefig('results/cnn_vs_xgb_accuracy_snr.png', dpi=150)\n"
    "    plt.show()\n"
    "\n"
    "    print('=' * 50)\n"
    "    print('MODEL ACCURACY SUMMARY')\n"
    "    print('=' * 50)\n"
    "    print(f'  Random Forest (6 features, old) : 54.79%')\n"
    "    print(f'  Random Forest (31 features)     : {acc_rf*100:.2f}%')\n"
    "    if XGBOOST_AVAILABLE:\n"
    "        print(f'  XGBoost       (31 features)     : {acc_xgb*100:.2f}%')\n"
    "    print(f'  1D CNN        (raw I/Q)         : {cnn_acc*100:.2f}%')\n"
    "    print('=' * 50)\n"
))

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print(f"Done. Total cells: {len(nb['cells'])}")
